spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:dbteste
        username: sa
        password:

    jpa:
        #somente em dev
        defer-datasource-initialization: true

        database: h2
        database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
        ddl-auto: update

    sql:
        init:
            mode: always

    properties:
        hibernate:
            show_sql: true
            format_sql: true

    h2:
        console:
            enabled: true
